module wolfie;

extern fn void irq_0();
extern fn void irq_1();
extern fn void irq_2();
extern fn void irq_3();
extern fn void irq_4();
extern fn void irq_5();
extern fn void irq_6();
extern fn void irq_7();
extern fn void irq_8();
extern fn void irq_9();
extern fn void irq_10();
extern fn void irq_11();
extern fn void irq_12();
extern fn void irq_13();
extern fn void irq_14();
extern fn void irq_15();
